In [1]:
import pandas as pd

# Read a .csv from a URL with Pandas

In [7]:
#reading 1 csv file from the website
df_premier25 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')

In [8]:
# showing dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [9]:
# rename columns
df_premier25.rename(columns = {'FTHG':'home_goals',
                              'FTAG':'away_goals'}, inplace = True)

In [10]:
# show dataframe
df_premier25

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

## Read .csv from Multiple URLs with Pandas

- LInk: root + season + league

In [14]:
# link strucure
"https://football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

'https://football-data.co.uk/mmz4281/2526/E0.csv'

In [2]:
# create a root variable
root = "https://football-data.co.uk/mmz4281/"
season = "2526/"

### Multiple leagues

In [7]:
# create list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']
frames =[]
# looping through leagues, read multiple csv and append it into a list
for league in leagues:
    df = pd.read_csv(root + season + league + '.csv')
    frames.append(df)

In [8]:
# length of frames
len(frames)

5

In [9]:
# show 1st, 2nd and 3rd element
frames[0]
frames[4]

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,0,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,0,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,0,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,1,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,EC,25/04/2026,12:30,Scunthorpe,Eastleigh,0,1,A,0,1,...,1.85,1.95,NaN,NaN,1.85,1.95,1.80,1.88,NaN,NaN
548,EC,25/04/2026,12:30,Southend,Wealdstone,2,1,H,2,1,...,1.83,1.98,NaN,NaN,1.83,1.98,1.78,1.91,NaN,NaN
549,EC,25/04/2026,12:30,Tamworth,Braintree Town,5,1,H,2,1,...,1.78,2.03,NaN,NaN,1.83,2.03,1.77,1.93,NaN,NaN
550,EC,25/04/2026,12:30,Woking,Halifax,0,1,A,0,0,...,2.08,1.73,NaN,NaN,2.08,1.75,1.99,1.72,NaN,NaN
551,EC,25/04/2026,12:30,Yeovil,Solihull,1,4,A,1,4,...,1.78,2.03,NaN,NaN,1.78,2.03,1.73,1.97,NaN,NaN

### Multiple Seasons

In [17]:
# create list of leagues
leagues = ['E0', 'E2', 'E3']
frames =[]
#Looping through multiple seasons
for season in range(15, 21):
# looping through leagues, read multiple csv and append it into a list
    for league in leagues:
        url = root + str(season) + str(season + 1) + '/' + league + '.csv'
        print(url)
        df = pd.read_csv(url)
        df.insert(1, 'season', season)
        frames.append(df)

https://football-data.co.uk/mmz4281/1516/E0.csv
https://football-data.co.uk/mmz4281/1516/E2.csv
https://football-data.co.uk/mmz4281/1516/E3.csv
https://football-data.co.uk/mmz4281/1617/E0.csv
https://football-data.co.uk/mmz4281/1617/E2.csv
https://football-data.co.uk/mmz4281/1617/E3.csv
https://football-data.co.uk/mmz4281/1718/E0.csv
https://football-data.co.uk/mmz4281/1718/E2.csv
https://football-data.co.uk/mmz4281/1718/E3.csv
https://football-data.co.uk/mmz4281/1819/E0.csv
https://football-data.co.uk/mmz4281/1819/E2.csv
https://football-data.co.uk/mmz4281/1819/E3.csv
https://football-data.co.uk/mmz4281/1920/E0.csv
https://football-data.co.uk/mmz4281/1920/E2.csv
https://football-data.co.uk/mmz4281/1920/E3.csv
https://football-data.co.uk/mmz4281/2021/E0.csv
https://football-data.co.uk/mmz4281/2021/E2.csv
https://football-data.co.uk/mmz4281/2021/E3.csv

In [19]:
# total frames (6 season * 3 leagues)
len(frames)

18

In [21]:
# show 1st, and last element (new season column was created)
frames[0]
frames[len(frames) - 1]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

## Organize All the Data in Dictionary

In [3]:
# create a dictionary with original name of league as key
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [4]:
# get a dictionary element
dict_countries['Spanish La Liga']

'SP1'

In [6]:
for league in dict_countries:
    print(dict_countries[league])

SP1
SP2
D1
E0
E2
E3

In [7]:
dict_historical_data = {}
for league in dict_countries:
    frames = []
    for season in range(15,21):
        url = root + str(season) + str(season + 1) + '/' + dict_countries[league] + '.csv'
        df = pd.read_csv(url)
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames) # storing all seasons of a league in a single dataframe
    dict_historical_data[league] = df_concat # assigning dataframe to a new dictionary

In [10]:
# show dataframe inside dict_historical_data
dict_historical_data['German Bundesliga']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,D1,15,14/08/15,Bayern Munich,Hamburg,5,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,D1,15,15/08/15,Augsburg,Hertha,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D1,15,15/08/15,Darmstadt,Hannover,2,2,D,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D1,15,15/08/15,Dortmund,M'gladbach,4,0,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D1,15,15/08/15,Leverkusen,Hoffenheim,2,1,H,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,D1,20,22/05/2021,Hoffenheim,Hertha,2,1,H,0,1,...,2.96,-0.75,1.86,2.07,1.88,2.06,1.99,2.08,1.88,2.00
302,D1,20,22/05/2021,Stuttgart,Bielefeld,0,2,A,0,0,...,2.50,-0.25,2.03,1.90,2.02,1.90,2.06,1.91,2.01,1.87
303,D1,20,22/05/2021,Union Berlin,RB Leipzig,2,1,H,0,0,...,2.34,0.50,1.97,1.96,1.97,1.95,1.98,1.98,1.92,1.95
304,D1,20,22/05/2021,Werder Bremen,M'gladbach,2,4,A,0,1,...,2.52,0.25,2.04,1.89,2.03,1.90,2.07,1.91,2.00,1.87
305,D1,20,22/05/2021,Wolfsburg,Mainz,2,3,A,0,1,...,2.97,-0.75,2.05,1.75,2.09,1.83,2.13,1.89,2.04,1.83